#!/bin/bash

commit_msg_file="$1"

# 从提交消息文件中提取关键信息
rootCause=$(grep -E "^\\[rootCause\\]: (.+)$" "$commit_msg_file" | sed -E 's/\[rootCause\]: (.+)/\1/')
solution=$(grep -E "^\\[solution\\]: (.+)$" "$commit_msg_file" | sed -E 's/\[solution\]: (.+)/\1/')
issueNumber=$(grep -E "^\\[issueNumber\\]: (.+)$" "$commit_msg_file" | sed -E 's/\[issueNumber\]: (.+)/\1/')
release=$(grep -E "^\\[release\\]: (.+)$" "$commit_msg_file" | sed -E 's/\[release\]: (.+)/\1/')

# 检查提交消息是否符合模板
if ! grep -Eq "^\[rootCause\]: .+" "$commit_msg_file" ||
   ! grep -Eq "^\[solution\]: .+" "$commit_msg_file" ||
   ! grep -Eq "^\[issueNumber\]: .+" "$commit_msg_file" ||
   ! grep -Eq "^\[release\]: .+" "$commit_msg_file"; then
  echo "提交commit不符合模板規範，請檢查[rootCause]:、[solution]:、[issueNumber]:、[release]:是否存在，且每一個[key]: 後面需空格。"
  exit 1
fi

if [[ "$rootCause" == *"feat"* && ("$issueNumber" == "N/A" || -z "$issueNumber") ]]; then
  echo "提交commit不符合模板規範，rootCause為feat時，issueNumber不能為N/A或空。"
  exit 1
fi


# 从提交消息中提取提交类型
commit_type=$(echo "$rootCause" | cut -d' ' -f1)

# 检查提交类型是否合法
if ! [[ "$commit_type" =~ ^(feat|fix|docs|style|refactor|perf|test|chore|revert)$ ]]; then
  echo "提交commit不符合模板規範，請檢查提交的類型是否包含feat|fix|docs|style|refactor|perf|test|chore|revert。"
  exit 1
fi
