#!/bin/bash

commit_msg_file="$1"

# 从提交消息文件中提取关键信息
rootCause=$(grep -E "^\\[rootCause\\]: (.+)$" "$commit_msg_file" | sed -E 's/\[rootCause\]: (.+)/\1/')
solution=$(grep -E "^\\[solution\\]: (.+)$" "$commit_msg_file" | sed -E 's/\[solution\]: (.+)/\1/')
issueNumber=$(grep -E "^\\[issueNumber\\]: (.+)$" "$commit_msg_file" | sed -E 's/\[issueNumber\]: (.+)/\1/')
release=$(grep -E "^\\[release\\]: (.+)$" "$commit_msg_file" | sed -E 's/\[release\]: (.+)/\1/')

# 4个字段的key值必填
if [[ "$rootCause" == "N/A" || -z "$rootCause" || "$solution" == "N/A" || -z "$solution" || "$issueNumber" == "N/A" || -z "$issueNumber" || "$release" == "N/A" || -z "$release" ]]; then
  echo "提交消息不符合模板規範，請檢查key值是否有遺漏。"
  exit 1
fi

# 从提交消息中提取提交类型
commit_type=$(echo "$rootCause" | cut -d' ' -f1)

# 检查提交类型是否合法
if ! [[ "$commit_type" =~ ^(feat|fix|docs|style|refactor|perf|test|chore|revert)$ ]]; then
  echo "請檢查提交的類型是否合法。"
  exit 1
fi
